spring.application.name=projeto1
# create database bdtestespring2 -- comentário
spring.jpa.open-in-view=true

# Configurações do banco de dados SQL Server
spring.datasource.url=jdbc:sqlserver://DESKTOP-2L5IB4R\\SQLEXPRESS:1433;databaseName=bdtestespring2;encrypt=true;trustServerCertificate=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=*
spring.datasource.password=dba
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=create-drop

# Se você também estiver servindo páginas web, pode querer configurar o filtro de codificação de caracteres
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true
